AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "Casks/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 118

Metrics/AbcSize:
  Exclude:
    - "scripts/**/*.rb"

Metrics/ClassLength:
  Exclude:
    - "scripts/**/*.rb"

Metrics/MethodLength:
  Exclude:
    - "scripts/**/*.rb"

Metrics/CyclomaticComplexity:
  Exclude:
    - "scripts/**/*.rb"

Metrics/PerceivedComplexity:
  Exclude:
    - "scripts/**/*.rb"
