name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  brew:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - uses: Homebrew/actions/setup-homebrew@main
        with:
          core: false
          cask: true

      - name: brew style
        run: brew style --cask imbytecat/tap

      - name: brew audit
        run: brew audit --cask --online imbytecat/tap/ugreen-nas
